---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lengyouyi.
--- DateTime: 2022/3/18 10:42
---
---
--- 角色类型
local BillardsType = {}

BillardsType.BilliardsPlayerType = {
    SELF = 1,   --自己
    OTHER = 2   --对方
}

--- 台球类型
BillardsType.BillardsBallType = {
    NONE = 0,
    WHITE_BALL = 0,--白球
    SINGLE_BALL = 1, --单球
    BLACK_BALL= 2,--黑球
    COLOR_BALL = 3, --彩球
}

--- 游戏状态类型
BillardsType.BilliardsGameType = {
    SWING_BALL = 1,--摆球 --开局摆球
    HIT_BALLS = 2, --打球阶段
    FREE_BALL = 3,--任意球
    END = 4,--战局结束
}

--- 游戏回合阶段
BillardsType.RoundPhase = {
    READY = 0,
    FREE_BALL = 1,
    HIT_BALLS = 2,
    BALL_MOVING = 3,
}

--- 游戏事件类型
BillardsType.BilliardsEvent = {
    E_1 = 1, --黑八进
    E_2 = 2, --没进球
    E_3 = 3, --白球进
    E_4 = 4, --进的不是自己的球
    E_5 = 5, --进球了
    E_6 = 6,--显示打的球类型
}

--- 游戏类型
BillardsType.BillardsModuleType = {
    NORMAL = 1,  --普通模式
    EASY = 2   --简单模式
}

--玩家类型
BillardsType.USER_IDENTITY = {
    Viewer = 0, --观众
    Player = 1, --玩家
    Host = 2--游戏房主
}
---犯规类型
BillardsType.BreakRuleType = 
{
    ReStart = 1, --开球犯规, 对方重新开球
    WhiteBallIn = 2, --母球进袋
    Black8In = 3, --黑8进袋
    Delay = 4, --击球超时
    NoBallHit = 5, --未击中任何球
    NotOwnedBall = 6, ---不是自己的球
    RestartDelay = 7 --开球超时
}

----击球状态
BillardsType.BattleStatus = 
{
    Moving = 0,
    Stop = 1
}

--台球玩法类型
BillardsType.ModelType = {
    NORMAL = 1,
    EASY = 2
}

BillardsType.FieldType = "difficulty" --台球类型

return BillardsType