---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lengyouyi.
--- DateTime: 2022/3/29 12:01
---

local BillardsEvent = 
{
    BillardsEventType = 
    {
        GAME_STATE_CHANGE = "E_CHANGE_GAME_STATUS",
        E_SHOW_CUE = "E_SHOW_CUE", ---显示球杆
        E_CHANGE_PLAYER= "E_CHANGE_PLAYER", ---切换玩家
        E_Enter_Ball = "E_Enter_Ball",

        E_BeginGame = "E_BeginGame",    ---游戏开始
        E_NoticeShotBall = "E_NoticeShotBall", --通知击球
        E_UpdateBall = "E_UpdateBall", ---同步通知
        E_SeprateBall = "E_SeprateBall", ---分球消息
        E_WhiteBallMove = "E_WhiteBallMove",  ---母球移动
        E_BreakRule = "E_BreakRule",  ---犯规消息
        E_GameOver = "E_GameOver",   ---游戏结束
        E_ChangeAngle = "E_ChangeAngle", --改变球的角度

        E_GamtTypeChanged = "E_GamtTypeChanged", --游戏类型改变（普通，容易）
        
        E_NoticeHit = "E_NoticeHit",

        E_OpenMainPage = "E_OpenMainPage",

        E_Billiards_Reconnection = "E_Billiards_Reconnection", ---断线重连通知

        E_EnterBattle = "E_EnterBattle",

        E_SyncRound = "E_SyncRound", --同步回合数据，断线或者重连

        E_BeginRound = "E_BeginRound",

        E_EndRound = "E_EndRound",

        E_ExitGame = "E_ExitGame",
    }
}

return BillardsEvent