---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lengyouyi.
--- DateTime: 2022/3/21 20:31
---
local BillardsCfg = {

    BilliardsValueCfg = {
        MAX_F = 1500,       --最大力
    },
    
    BilliardsEventCfg = {
        E_1 = "黑8进",
        E_2 = "没有进球 轮到对手",
        E_3 = "白球进洞 对手任意",
        E_4 = "没击中自己的 轮到对手",
        E_5 = "进球了",
        E_6 = "显示打的球类型"
    },
    
    BilliardsTypeCfg = {
        [0] = "彩球",
        [1] = "单球",
    }
}

return BillardsCfg
