using("BilliardsBall", "Game.Billiards.Basic.BilliardsBall")
using("BilliardsTable", "Game.Billiards.Basic.BilliardsTable")
using("BilliardsUpdate", "Game.Billiards.Basic.BilliardsUpdate")
using("BilliardsGame", "Game.Billiards.BilliardsGame")
using("BillardsCfg", "Game.Billiards.Common.BillardsCfg")
using("BillardsEvent", "Game.Billiards.Common.BillardsEvent")
using("BillardsType", "Game.Billiards.Common.BillardsType")
using("UIBilliardsContainer", "Game.Billiards.Module.UI.UIBilliardsContainer")
using("UIBilliardsMain", "Game.Billiards.Module.UI.UIBilliardsMain")
using("UIBilliardsMenu", "Game.Billiards.Module.UI.UIBilliardsMenu")
using("UIBilliardsPrompt", "Game.Billiards.Module.UI.UIBilliardsPrompt")
using("UIBilliardsReady", "Game.Billiards.Module.UI.UIBilliardsReady")
using("UIBilliardsResult", "Game.Billiards.Module.UI.UIBilliardsResult")
using("UIBilliardsRule", "Game.Billiards.Module.UI.UIBilliardsRule")
using("UIBilliardsSelect", "Game.Billiards.Module.UI.UIBilliardsSelect")
using("BillardsUtil", "Game.Billiards.Module.Util.BillardsUtil")
using("BilliardsAudio", "Game.Billiards.Module.Util.BilliardsAudio")
using("BilliardsBattle", "Game.Billiards.Module.Vo.BilliardsBattle")
using("BilliardsPlayer", "Game.Billiards.Module.Vo.BilliardsPlayer")
using("BilliardsNetDefine", "Game.Billiards.Net.BilliardsNetDefine")
using("BilliardsProxy", "Game.Billiards.Net.BilliardsProxy")
using("Billiards8Rule", "Game.Billiards.Rules.Billiards8Rule")
using("BilliardsRule", "Game.Billiards.Rules.BilliardsRule")
using("BaseUIBilliardsContainer", "Game.Billiards.Views.BaseUIBilliardsContainer")
using("BaseUIBilliardsMain", "Game.Billiards.Views.BaseUIBilliardsMain")
using("BaseUIBilliardsMenu", "Game.Billiards.Views.BaseUIBilliardsMenu")
using("BaseUIBilliardsPrompt", "Game.Billiards.Views.BaseUIBilliardsPrompt")
using("BaseUIBilliardsReady", "Game.Billiards.Views.BaseUIBilliardsReady")
using("BaseUIBilliardsResult", "Game.Billiards.Views.BaseUIBilliardsResult")
using("BaseUIBilliardsRule", "Game.Billiards.Views.BaseUIBilliardsRule")
using("BaseUIBilliardsSelect", "Game.Billiards.Views.BaseUIBilliardsSelect")

return function()
	unusing("BilliardsBall")
	unusing("BilliardsTable")
	unusing("BilliardsUpdate")
	unusing("BilliardsGame")
	unusing("BillardsCfg")
	unusing("BillardsEvent")
	unusing("BillardsType")
	unusing("UIBilliardsContainer")
	unusing("UIBilliardsMain")
	unusing("UIBilliardsMenu")
	unusing("UIBilliardsPrompt")
	unusing("UIBilliardsReady")
	unusing("UIBilliardsResult")
	unusing("UIBilliardsRule")
	unusing("UIBilliardsSelect")
	unusing("BillardsUtil")
	unusing("BilliardsAudio")
	unusing("BilliardsBattle")
	unusing("BilliardsPlayer")
	unusing("BilliardsNetDefine")
	unusing("BilliardsProxy")
	unusing("Billiards8Rule")
	unusing("BilliardsRule")
	unusing("BaseUIBilliardsContainer")
	unusing("BaseUIBilliardsMain")
	unusing("BaseUIBilliardsMenu")
	unusing("BaseUIBilliardsPrompt")
	unusing("BaseUIBilliardsReady")
	unusing("BaseUIBilliardsResult")
	unusing("BaseUIBilliardsRule")
	unusing("BaseUIBilliardsSelect")
end
