namespace Spark.Tweening
{
	[XLua.LuaCallCSharp]
	public enum Ease
	{
		//Unset = 0,
		Linear = 1,
		SineIn = 2,
		SineOut = 3,
		SineInOut = 4,
		QuadIn = 5,
		QuadOut = 6,
		QuadInOut = 7,
		CubicIn = 8,
		CubicOut = 9,
		CubicInOut = 10,
		QuartIn = 11,
		QuartOut = 12,
		QuartInOut = 13,
		QuintIn = 14,
		QuintOut = 15,
		QuintInOut = 16,
		ExpoIn = 17,
		ExpoOut = 18,
		ExpoInOut = 19,
		CircIn = 20,
		CircOut = 21,
		CircInOut = 22,
		ElasticIn = 23,
		ElasticOut = 24,
		ElasticInOut = 25,
		BackIn = 26,
		BackOut = 27,
		BackInOut = 28,
		BounceIn = 29,
		BounceOut = 30,
		BounceInOut = 31,
		Flash = 32,
		FlashIn = 33,
		FlashOut = 34,
		FlashInOut = 35,
	}
}
